### ISSUE TITLE
No output when using plot macro in tests.

### ISSUE THREAD

**Issue by the-drunk-coder** [fabianboesiger/debug-plotter#4]
I've been trying to use `debug_plotter::plot!()` in one of my tests, but I don't get any output. Am I doing something wrong ? It compiles and runs fine otherwise ... 

Best,
N

**Comment by fabianboesiger** [comment]
Hi, did you run your code in release mode?

**Comment by fabianboesiger** [comment]
I never used the macro in a test, maybe there is some bug hidden there. I'll check it out myself.

**Comment by the-drunk-coder** [comment]
Hi, the latest version from git (0.3.0) actually works, but the version published on crates.io (0.2.1) doesn't ...

**Comment by fabianboesiger** [comment]
Oh, okay. The problem is I can't update the version on Crates.io because the project depends on a newer version of [plotters-piston](https://github.com/plotters-rs/plotters-piston) that is not available on Crates.io. And I can't update the crate as long as it contains a dependency directly from github.

**Comment by the-drunk-coder** [comment]
Ah, yes, I've run into that one before. Anyway, good to know that it works.

Great tool, by the way! Helps a lot with debugging DSP stuff.

**Comment by fabianboesiger** [comment]
In that case I'll close this issue. Maybe I'll simply copy the code from the other inactive project so that I can update the Crates.io verison in the future ...

Anyway, thanks for the feedback, always nice to hear :-)
